In [ ]:
# ============================================================
# Export CSV final — 2013
# ============================================================

nom_export = "GVH_Jovian_Observables_2013.csv"

observables_gvh_2013.to_csv(
    nom_export,
    index=False,
    float_format="%.12g"
)

print("Export terminé :", nom_export)

Export terminé : GVH_Jovian_Observables_2013.csv

In [ ]:
# ============================================================
# Exports détaillés optionnels
# ============================================================

transitions_2013 = pd.concat(
    [
        transitions_io_2013,
        transitions_europa_2013,
        transitions_ganymede_2013
    ],
    ignore_index=True
)

angles_2013 = pd.concat(
    [
        angles_io_2013,
        angles_europa_2013,
        angles_ganymede_2013
    ],
    ignore_index=True
)

phases_2013 = pd.concat(
    [
        phase_io_2013,
        phase_europa_2013,
        phase_ganymede_2013
    ],
    ignore_index=True
)

transitions_2013.to_csv(
    "GVH_Jovian_Transitions_2013.csv",
    index=False,
    float_format="%.12g"
)

angles_2013.to_csv(
    "GVH_Jovian_Angles_2013.csv",
    index=False,
    float_format="%.12g"
)

phases_2013.to_csv(
    "GVH_Jovian_Orbital_Phases_2013.csv",
    index=False,
    float_format="%.12g"
)

print("Exports détaillés terminés.")

Exports détaillés terminés.

In [ ]:
observables_gvh_2013

,Satellite,Annee,Source,N_etats,N_transitions,N_angles,Quantile,D_T_mean,S_T,S_T_norm,...,theta_min,theta_max,R_170,R_175,R_180,omega_rad_h,periode_heures,periode_jours,R2_angle_temps,residu_angle_std_rad
0,Io,2013,NASA/JPL Horizons,8761,8760,8759,0.95,62356.262729,182.664421,0.002917,...,8.443697,8.514382,0.0,0.0,0.0,0.147981,42.459325,1.769139,1.0,0.005855
1,Europa,2013,NASA/JPL Horizons,8761,8760,8759,0.95,49460.410278,322.925376,0.006465,...,4.184519,4.265604,0.0,0.0,0.0,0.073722,85.228210,3.551175,1.0,0.013017
2,Ganymede,2013,NASA/JPL Horizons,8761,8760,8759,0.95,39166.885653,55.563145,0.001415,...,2.091087,2.102381,0.0,0.0,0.0,0.036592,171.709270,7.154553,1.0,0.002855

In [ ]:
from pathlib import Path

dossier = Path(
    "/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026"
)
dossier.mkdir(parents=True, exist_ok=True)

chemin = dossier / "GVH_Jovian_Observables_2013.csv"

observables_gvh_2013.to_csv(
    chemin,
    index=False,
    float_format="%.12g"
)

print("Export terminé :", chemin)
print("Fichier présent :", chemin.exists())

Export terminé : /content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Jovian_Observables_2013.csv
Fichier présent : True

In [ ]:
resultats_2013 = pd.read_csv(
    "/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/"
    "GVH_Jovian_Observables_2013.csv"
)

print(resultats_2013.shape)
display(resultats_2013)

(3, 27)

,Satellite,Annee,Source,N_etats,N_transitions,N_angles,Quantile,D_T_mean,S_T,S_T_norm,...,theta_min,theta_max,R_170,R_175,R_180,omega_rad_h,periode_heures,periode_jours,R2_angle_temps,residu_angle_std_rad
0,Io,2013,NASA/JPL Horizons,8761,8760,8759,0.95,62356.262729,182.664421,0.002917,...,8.443697,8.514382,0,0,0,0.147981,42.459325,1.769139,1.0,0.005855
1,Europa,2013,NASA/JPL Horizons,8761,8760,8759,0.95,49460.410278,322.925376,0.006465,...,4.184519,4.265604,0,0,0,0.073722,85.228210,3.551175,1.0,0.013017
2,Ganymede,2013,NASA/JPL Horizons,8761,8760,8759,0.95,39166.885653,55.563145,0.001415,...,2.091087,2.102381,0,0,0,0.036592,171.709270,7.154553,1.0,0.002855

In [ ]:
%whos DataFrame

Variable                      Type         Data/Info
----------------------------------------------------
angles_2013                   DataFrame          Satellite     Datet<...>n[26277 rows x 3 columns]
angles_europa_2013            DataFrame         Satellite     Dateti<...>\n[8759 rows x 3 columns]
angles_ganymede_2013          DataFrame         Satellite     Dateti<...>\n[8759 rows x 3 columns]
angles_io_2013                DataFrame         Satellite     Dateti<...>\n[8759 rows x 3 columns]
europa_2013                   DataFrame                    JD       <...>n[8761 rows x 11 columns]
europa_2013_brut              DataFrame                    0        <...>n[8761 rows x 12 columns]
ganymede_2013                 DataFrame                    JD       <...>n[8761 rows x 11 columns]
ganymede_2013_brut            DataFrame                    0        <...>n[8761 rows x 12 columns]
io_2013                       DataFrame                    JD       <...>n[8761 rows x 11 columns]
io_2013_brut                  DataFrame                    0        <...>n[8761 rows x 12 columns]
observables_angulaires_2013   DataFrame      Satellite  N_angles  th<...>81    0.0    0.0    0.0
observables_gvh_2013          DataFrame      Satellite  Annee       <...>\n\n[3 rows x 27 columns]
observables_gvh_2013_base     DataFrame      Satellite  N_etats  N_t<...>4142  0.999535     0.05
periodes_orbitales_2013       DataFrame      Satellite  omega_rad_h <...>2              0.002855
phase_europa_2013             DataFrame         Satellite           <...>\n[8761 rows x 7 columns]
phase_ganymede_2013           DataFrame         Satellite           <...>\n[8761 rows x 7 columns]
phase_io_2013                 DataFrame         Satellite           <...>\n[8761 rows x 7 columns]
phases_2013                   DataFrame          Satellite          <...>n[26283 rows x 7 columns]
resultats_2013                DataFrame      Satellite  Annee       <...>\n\n[3 rows x 27 columns]
statistiques_physiques_2013   DataFrame      Satellite  N_transition<...>6791  \n2  39269.493093
transitions_2013              DataFrame          Satellite      Date<...>[26280 rows x 12 columns]
transitions_europa_2013       DataFrame         Satellite      Datet<...>n[8760 rows x 12 columns]
transitions_ganymede_2013     DataFrame         Satellite      Datet<...>n[8760 rows x 12 columns]
transitions_io_2013           DataFrame         Satellite      Datet<...>n[8760 rows x 12 columns]

In [ ]:
# ============================================================
# Recherche élargie des exports Europa et Ganymède
# ============================================================

from pathlib import Path

racine_drive = Path("/content/drive/MyDrive")

motifs = [
    "*Europa*.csv",
    "*Ganymede*.csv",
    "*Europe*.csv",
    "*Ganymède*.csv"
]

fichiers = []

for motif in motifs:
    fichiers.extend(racine_drive.rglob(motif))

fichiers = sorted(set(fichiers))

print(f"Nombre de fichiers trouvés : {len(fichiers)}\n")

for fichier in fichiers:
    print(fichier)

Nombre de fichiers trouvés : 11

/content/drive/MyDrive/    NASA_JPL_Europa_StateVectors_2013.csv
/content/drive/MyDrive/    NASA_JPL_Ganymede_StateVectors_2013.csv
/content/drive/MyDrive/Europa_Horizons_Jovicentric_Vector_2026_1h_RAW.csv
/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Europa_Angles_2000.csv
/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Europa_Transitions_2000.csv
/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Ganymede_Angles_2000.csv
/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Ganymede_Transitions_2000.csv
/content/drive/MyDrive/Ganymede_Horizons_Jovicentric_Vector_2026_1h_RAW.csv
/content/drive/MyDrive/JPL_Horizons_Europa_2000_1h.csv
/content/drive/MyDrive/JPL_Horizons_Ganymede_2000_1h.csv
/content/drive/MyDrive/Saved from Chrome/GVH_Ganymede_Angles_0.1.csv

In [ ]:
# ============================================================
# Recherche de tous les CSV contenant "Observables"
# ============================================================

fichiers_observables = sorted(
    Path("/content/drive/MyDrive").rglob("*Observables*.csv")
)

print(f"Nombre de fichiers observables trouvés : {len(fichiers_observables)}\n")

for fichier in fichiers_observables:
    print(fichier)

Nombre de fichiers observables trouvés : 4

/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Jovian_Observables_2000.csv
/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Jovian_Observables_2013.csv
/content/drive/MyDrive/GVH_Lunar_Libration_Real_Data_0.1/GVH_Lunar_Libration_Observables_0.1.csv
/content/drive/MyDrive/Saved from Chrome/GVH_Io_Observables_0.1.csv

In [ ]:
ANNEE = 2026

In [ ]:
chemin_europa = "/content/drive/MyDrive/Europa_Horizons_Jovicentric_Vector_2026_1h_RAW.csv"
chemin_ganymede = "/content/drive/MyDrive/Ganymede_Horizons_Jovicentric_Vector_2026_1h_RAW.csv"

In [ ]:
# ============================================================
# Étape 1 — Inspection du fichier brut Europa 2026
# ============================================================

from pathlib import Path

chemin_europa_2026 = Path(
    "/content/drive/MyDrive/"
    "Europa_Horizons_Jovicentric_Vector_2026_1h_RAW.csv"
)

print("Fichier présent :", chemin_europa_2026.exists())
print("Chemin :", chemin_europa_2026)

if not chemin_europa_2026.exists():
    raise FileNotFoundError(
        f"Fichier introuvable : {chemin_europa_2026}"
    )

with open(
    chemin_europa_2026,
    "r",
    encoding="utf-8",
    errors="replace"
) as fichier:
    lignes = fichier.readlines()

print("Nombre total de lignes :", len(lignes))

print("\n===== 25 PREMIÈRES LIGNES =====\n")

for numero, ligne in enumerate(lignes[:25], start=1):
    print(f"{numero:02d} | {ligne.rstrip()}")

print("\n===== REPÈRES HORIZONS =====\n")

for repere in ["$$SOE", "$$EOE"]:
    positions = [
        i + 1
        for i, ligne in enumerate(lignes)
        if repere in ligne
    ]

    print(repere, ":", positions)

Fichier présent : True
Chemin : /content/drive/MyDrive/Europa_Horizons_Jovicentric_Vector_2026_1h_RAW.csv
Nombre total de lignes : 8867

===== 25 PREMIÈRES LIGNES =====

01 | *******************************************************************************
02 |  Revised: Mar 12, 2021           Europa / (Jupiter)                         502
03 |
04 |  SATELLITE PHYSICAL PROPERTIES:
05 |   Mean radius (km)       = 1560.8   +- 0.3    Density (g cm^-3)= 3.013 +- 0.005
06 |   GM   (km^3/s^2)        = 3202.7121+- 0.0054 Geometric Albedo = 0.67 +/- 0.03
07 |
08 |  SATELLITE ORBIT (at J2000.0 epoch, 2000-Jan-1.5):
09 |   Semi-major axis, a (km) ~ 671,000           Orbital period   ~ 3.55 d
10 |   Eccentricity, e         ~ 0.00981        Rotational period   = Synchronous
11 |   Inclination, i  (deg)   ~ 0.462
12 | *******************************************************************************
13 |
14 |
15 | *******************************************************************************
16 | Ephemeris / WWW_USER Fri Jul 17 06:55:26 2026 Pasadena, USA      / Horizons
17 | *******************************************************************************
18 | Target body name: Europa (502)                    {source: jup365_merged}
19 | Center body name: Jupiter (599)                   {source: jup365_merged}
20 | Center-site name: BODY CENTER
21 | *******************************************************************************
22 | Start time      : A.D. 2026-Jan-01 00:00:00.0000 TDB
23 | Stop  time      : A.D. 2027-Jan-01 00:00:00.0000 TDB
24 | Step-size       : 60 minutes
25 | *******************************************************************************

===== REPÈRES HORIZONS =====

$$SOE : [37]
$$EOE : [8799]

In [ ]:
# ============================================================
# Lecture du fichier Horizons brut (Europa 2026)
# ============================================================

import pandas as pd

# Lecture du fichier texte
with open(
    chemin_europa_2026,
    "r",
    encoding="utf-8",
    errors="replace"
) as f:
    lignes = f.readlines()

# Localisation des données
debut = next(i for i, l in enumerate(lignes) if "$$SOE" in l) + 1
fin = next(i for i, l in enumerate(lignes) if "$$EOE" in l)

# Extraction des lignes de données
donnees = [ligne.strip().split(",") for ligne in lignes[debut:fin]]

# DataFrame brut
europa_2026_brut = pd.DataFrame(donnees)

print("Dimensions :", europa_2026_brut.shape)
display(europa_2026_brut.head())

Dimensions : (8761, 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,2461041.500000000,A.D. 2026-Jan-01 00:00:00.0000,8.255014490144156E+04,-6.695272467844612E+05,-1.909031960506947E+04,1.354614589817800E+01,1.765537614893281E+00,3.398307001370476E-01,2.251114578713939E+00,6.748671727922863E+05,-1.042082222335571E-01,
1,2461041.541666667,A.D. 2026-Jan-01 01:00:00.0000,1.310521287209322E+05,-6.613878325062318E+05,-1.781701116224870E+04,1.338734369858335E+01,2.754622980721091E+00,3.672552518049880E-01,2.249829787973674E+00,6.744820022182467E+05,-1.096806492247049E-01,
2,2461041.583333333,A.D. 2026-Jan-01 02:00:00.0000,1.788526316502627E+05,-6.497096026372442E+05,-1.644838551818387E+04,1.315656409058775E+01,3.730674943792103E+00,3.927603266416324E-01,2.248482752951543E+00,6.740781712779498E+05,-1.145705361521491E-01,
3,2461041.625000000,A.D. 2026-Jan-01 03:00:00.0000,2.256941617911920E+05,-6.345488648436930E+05,-1.499161058146475E+04,1.285477330344653E+01,4.688485477369703E+00,4.162042452947456E-01,2.247080628061836E+00,6.736578248108415E+05,-1.188517683353880E-01,
4,2461041.666666667,A.D. 2026-Jan-01 04:00:00.0000,2.713233790393067E+05,-6.159805833800959E+05,-1.345434727490559E+04,1.248331115434487E+01,5.622901829856293E+00,4.374549019004228E-01,2.245630869691702E+00,6.732231981855530E+05,-1.225000205541323E-01,

In [ ]:
europa_2026 = nettoyer_horizons(europa_2026_brut)

print(europa_2026.shape)
display(europa_2026.head())

(8761, 11)

,JD,Datetime,X,Y,Z,VX,VY,VZ,LT,RG,RR
0,2.461042e+06,2026-01-01 00:00:00,82550.144901,-669527.246784,-19090.319605,13.546146,1.765538,0.339831,2.251115,674867.172792,-0.104208
1,2.461042e+06,2026-01-01 01:00:00,131052.128721,-661387.832506,-17817.011162,13.387344,2.754623,0.367255,2.249830,674482.002218,-0.109681
2,2.461042e+06,2026-01-01 02:00:00,178852.631650,-649709.602637,-16448.385518,13.156564,3.730675,0.392760,2.248483,674078.171278,-0.114571
3,2.461042e+06,2026-01-01 03:00:00,225694.161791,-634548.864844,-14991.610581,12.854773,4.688485,0.416204,2.247081,673657.824811,-0.118852
4,2.461042e+06,2026-01-01 04:00:00,271323.379039,-615980.583380,-13454.347275,12.483311,5.622902,0.437455,2.245631,673223.198186,-0.122500

In [ ]:
# ============================================================
# Construction des transitions — Europa 2026
# ============================================================

import numpy as np
import pandas as pd

def construire_transitions(df, satellite):
    colonnes_etat = ["X", "Y", "Z", "VX", "VY", "VZ"]

    variations = (
        df[colonnes_etat]
        .diff()
        .iloc[1:]
        .reset_index(drop=True)
    )

    variations.columns = [
        "dX", "dY", "dZ",
        "dVX", "dVY", "dVZ"
    ]

    transitions = pd.DataFrame({
        "Satellite": satellite,
        "Datetime": df["Datetime"].iloc[1:].reset_index(drop=True),
        "dX": variations["dX"],
        "dY": variations["dY"],
        "dZ": variations["dZ"],
        "dVX": variations["dVX"],
        "dVY": variations["dVY"],
        "dVZ": variations["dVZ"],
    })

    transitions["D_T"] = np.sqrt(
        transitions["dX"]**2
        + transitions["dY"]**2
        + transitions["dZ"]**2
    )

    return transitions


transitions_europa_2026 = construire_transitions(
    europa_2026,
    "Europa"
)

print("Dimensions :", transitions_europa_2026.shape)
print("Valeurs manquantes :", transitions_europa_2026.isna().sum().sum())
print("D_T moyen :", transitions_europa_2026["D_T"].mean())
print("D_T min :", transitions_europa_2026["D_T"].min())
print("D_T max :", transitions_europa_2026["D_T"].max())

display(transitions_europa_2026.head())

Dimensions : (8760, 9)
Valeurs manquantes : 0
D_T moyen : 49460.67299594374
D_T min : 48991.00315563903
D_T max : 49933.48347419306

,Satellite,Datetime,dX,dY,dZ,dVX,dVY,dVZ,D_T
0,Europa,2026-01-01 01:00:00,48501.983819,8139.414278,1273.308443,-0.158802,0.989085,0.027425,49196.684986
1,Europa,2026-01-01 02:00:00,47800.502929,11678.229869,1368.625644,-0.230780,0.976052,0.025505,49225.422998
2,Europa,2026-01-01 03:00:00,46841.530141,15160.737794,1456.774937,-0.301791,0.957811,0.023444,49255.447512
3,Europa,2026-01-01 04:00:00,45629.217248,18568.281464,1537.263307,-0.371462,0.934416,0.021251,49286.607934
4,Europa,2026-01-01 05:00:00,44169.054134,21882.446966,1609.633408,-0.439424,0.905949,0.018936,49318.736277

In [ ]:
# ============================================================
# Observables GVH de base — Europa 2026
# ============================================================

import numpy as np
import pandas as pd

def calculer_observables_gvh_base(
    transitions,
    satellite,
    quantile_seuil=0.95
):
    D_T = transitions["D_T"].to_numpy(dtype=float)

    # Observable moyenne
    D_T_mean = np.mean(D_T)

    # Dispersion absolue
    S_T = np.std(D_T, ddof=0)

    # Dispersion normalisée
    S_T_norm = S_T / D_T_mean if D_T_mean != 0 else np.nan

    # Normalisation dans [0, 1]
    D_T_min = np.min(D_T)
    D_T_max = np.max(D_T)

    amplitude = D_T_max - D_T_min

    if amplitude > 0:
        u = (D_T - D_T_min) / amplitude
    else:
        u = np.zeros_like(D_T)

    # Seuil critique
    u_c = np.quantile(u, quantile_seuil)

    # D_c exprimé dans l'unité physique de D_T
    D_c = D_T_min + u_c * amplitude

    # Fraction située au-dessus du seuil
    R_super = np.mean(u > u_c)

    observables = pd.DataFrame([{
        "Satellite": satellite,
        "Annee": 2026,
        "N_etats": len(transitions) + 1,
        "N_transitions": len(transitions),
        "D_T_mean": D_T_mean,
        "S_T": S_T,
        "S_T_norm": S_T_norm,
        "D_T_min": D_T_min,
        "D_T_max": D_T_max,
        "D_c": D_c,
        "u_c": u_c,
        "R_super": R_super
    }])

    transitions_gvh = transitions.copy()
    transitions_gvh["u"] = u
    transitions_gvh["supercritique"] = u > u_c

    return observables, transitions_gvh


observables_europa_2026_base, transitions_europa_2026_gvh = (
    calculer_observables_gvh_base(
        transitions_europa_2026,
        satellite="Europa",
        quantile_seuil=0.95
    )
)

display(observables_europa_2026_base)

print("\nContrôles :")
print("u min :", transitions_europa_2026_gvh["u"].min())
print("u max :", transitions_europa_2026_gvh["u"].max())
print(
    "Nombre de transitions supercritiques :",
    transitions_europa_2026_gvh["supercritique"].sum()
)

,Satellite,Annee,N_etats,N_transitions,D_T_mean,S_T,S_T_norm,D_T_min,D_T_max,D_c,u_c,R_super
0,Europa,2026,8761,8760,49460.672996,326.575789,0.006603,48991.003156,49933.483474,49917.132585,0.982651,0.05

Contrôles :
u min : 0.0
u max : 1.0
Nombre de transitions supercritiques : 438

In [ ]:
# ============================================================
# Observables angulaires — Europa 2026
# ============================================================

import numpy as np
import pandas as pd

def calculer_observables_angulaires(transitions, satellite, annee):
    vecteurs = transitions[["dX", "dY", "dZ"]].to_numpy(dtype=float)

    # Comparaison entre deux vecteurs de transition successifs
    v1 = vecteurs[:-1]
    v2 = vecteurs[1:]

    normes_v1 = np.linalg.norm(v1, axis=1)
    normes_v2 = np.linalg.norm(v2, axis=1)

    denominateur = normes_v1 * normes_v2

    # Évite toute division par zéro
    masque_valide = denominateur > 0

    cos_theta = np.full(len(denominateur), np.nan)

    cos_theta[masque_valide] = (
        np.sum(v1[masque_valide] * v2[masque_valide], axis=1)
        / denominateur[masque_valide]
    )

    # Correction des erreurs numériques éventuelles
    cos_theta = np.clip(cos_theta, -1.0, 1.0)

    theta_deg = np.degrees(np.arccos(cos_theta))
    theta_valide = theta_deg[np.isfinite(theta_deg)]

    if len(theta_valide) == 0:
        raise ValueError("Aucun angle valide n'a pu être calculé.")

    angles = pd.DataFrame({
        "Satellite": satellite,
        "Datetime": transitions["Datetime"].iloc[1:].reset_index(drop=True),
        "theta_deg": theta_deg
    })

    observables = pd.DataFrame([{
        "Satellite": satellite,
        "Annee": annee,
        "N_angles": len(theta_valide),
        "theta_mean": np.mean(theta_valide),
        "theta_median": np.median(theta_valide),
        "theta_std": np.std(theta_valide, ddof=0),
        "theta_min": np.min(theta_valide),
        "theta_max": np.max(theta_valide),
        "R_90": np.mean(theta_valide >= 90),
        "R_170": np.mean(theta_valide >= 170),
        "R_175": np.mean(theta_valide >= 175),
        "R_180": np.mean(theta_valide >= 179.9)
    }])

    return observables, angles


observables_europa_2026_angles, angles_europa_2026 = (
    calculer_observables_angulaires(
        transitions_europa_2026,
        satellite="Europa",
        annee=2026
    )
)

display(observables_europa_2026_angles)

print("\nContrôles :")
print("Nombre attendu d'angles :", len(transitions_europa_2026) - 1)
print("Nombre calculé :", angles_europa_2026["theta_deg"].notna().sum())
print("Valeurs manquantes :", angles_europa_2026["theta_deg"].isna().sum())

display(angles_europa_2026.head())

,Satellite,Annee,N_angles,theta_mean,theta_median,theta_std,theta_min,theta_max,R_90,R_170,R_175,R_180
0,Europa,2026,8759,4.224045,4.223538,0.027478,4.185695,4.264313,0.0,0.0,0.0,0.0

Contrôles :
Nombre attendu d'angles : 8759
Nombre calculé : 8759
Valeurs manquantes : 0

  Satellite            Datetime  theta_deg
0    Europa 2026-01-01 02:00:00   4.202639
1    Europa 2026-01-01 03:00:00   4.205097
2    Europa 2026-01-01 04:00:00   4.207668
3    Europa 2026-01-01 05:00:00   4.210333
4    Europa 2026-01-01 06:00:00   4.213081

In [ ]:
# ============================================================
# Fusion des observables Europa 2026
# ============================================================

observables_europa_2026 = (
    observables_europa_2026_base
    .merge(
        observables_europa_2026_angles,
        on=["Satellite", "Annee"],
        how="left"
    )
)

display(observables_europa_2026)

,Satellite,Annee,N_etats,N_transitions,D_T_mean,S_T,S_T_norm,D_T_min,D_T_max,D_c,...,N_angles,theta_mean,theta_median,theta_std,theta_min,theta_max,R_90,R_170,R_175,R_180
0,Europa,2026,8761,8760,49460.672996,326.575789,0.006603,48991.003156,49933.483474,49917.132585,...,8759,4.224045,4.223538,0.027478,4.185695,4.264313,0.0,0.0,0.0,0.0

In [ ]:
observables_europa_2026.to_csv(
    "/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Europa_Observables_2026.csv",
    index=False
)

print("Export terminé : GVH_Europa_Observables_2026.csv")

Export terminé : GVH_Europa_Observables_2026.csv

In [ ]:
# ============================================================
# Chargement du fichier brut — Ganymède 2026
# ============================================================

from pathlib import Path
import pandas as pd

chemin_ganymede_2026 = Path(
    "/content/drive/MyDrive/"
    "Ganymede_Horizons_Jovicentric_Vector_2026_1h_RAW.csv"
)

print("Fichier présent :", chemin_ganymede_2026.exists())
print("Chemin :", chemin_ganymede_2026)

if not chemin_ganymede_2026.exists():
    raise FileNotFoundError(
        f"Fichier introuvable : {chemin_ganymede_2026}"
    )

with open(
    chemin_ganymede_2026,
    "r",
    encoding="utf-8",
    errors="replace"
) as fichier:
    lignes = fichier.readlines()

debut = next(
    i for i, ligne in enumerate(lignes)
    if "$$SOE" in ligne
) + 1

fin = next(
    i for i, ligne in enumerate(lignes)
    if "$$EOE" in ligne
)

donnees = [
    ligne.strip().split(",")
    for ligne in lignes[debut:fin]
]

ganymede_2026_brut = pd.DataFrame(donnees)

print("Nombre total de lignes du fichier :", len(lignes))
print("Ligne $$SOE :", debut)
print("Ligne $$EOE :", fin + 1)
print("Dimensions brutes :", ganymede_2026_brut.shape)

display(ganymede_2026_brut.head())

Fichier présent : True
Chemin : /content/drive/MyDrive/Ganymede_Horizons_Jovicentric_Vector_2026_1h_RAW.csv
Nombre total de lignes du fichier : 8867
Ligne $$SOE : 37
Ligne $$EOE : 8799
Dimensions brutes : (8761, 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,2461041.500000000,A.D. 2026-Jan-01 00:00:00.0000,1.011876358680033E+06,-3.438550460846851E+05,1.524008883722767E+03,3.512205752289529E+00,1.030804459463613E+01,4.445608975065753E-01,3.564819290327548E+00,1.068705937373111E+06,9.471579443297561E-03,
1,2461041.541666667,A.D. 2026-Jan-01 01:00:00.0000,1.023836581183339E+06,-3.065229918278948E+05,3.123045106521837E+03,3.131621886767562E+00,1.042965585463984E+01,4.436928617975400E-01,3.564936430522270E+00,1.068741055120017E+06,1.003554843986617E-02,
2,2461041.583333333,A.D. 2026-Jan-01 02:00:00.0000,1.034419017552363E+06,-2.687783918671723E+05,4.717880592935951E+03,2.746855953728769E+00,1.053721114548444E+01,4.422274403808761E-01,3.565060247318970E+00,1.068778174461842E+06,1.058381158480567E-02,
3,2461041.625000000,A.D. 2026-Jan-01 03:00:00.0000,1.043609554624075E+06,-2.306721115515756E+05,6.306368327383912E+03,2.358432325635480E+00,1.063056710801335E+01,4.401667544793488E-01,3.565190561093817E+00,1.068817241548715E+06,1.111789779260714E-02,
4,2461041.666666667,A.D. 2026-Jan-01 04:00:00.0000,1.051395975902108E+06,-1.922554973842170E+05,7.886370395710648E+03,1.966880157111059E+00,1.070959980818920E+01,4.375137373152431E-01,3.565327211163317E+00,1.068858208208936E+06,1.163937335099921E-02,

In [ ]:
# ============================================================
# Nettoyage — Ganymède 2026
# ============================================================

ganymede_2026 = nettoyer_horizons(ganymede_2026_brut)

print("Dimensions nettoyées :", ganymede_2026.shape)
print("Début :", ganymede_2026["Datetime"].min())
print("Fin   :", ganymede_2026["Datetime"].max())
print("Valeurs manquantes :", ganymede_2026.isna().sum().sum())
print("Doublons :", ganymede_2026.duplicated().sum())

display(ganymede_2026.head())

Dimensions nettoyées : (8761, 11)
Début : 2026-01-01 00:00:00
Fin   : 2027-01-01 00:00:00
Valeurs manquantes : 0
Doublons : 0

,JD,Datetime,X,Y,Z,VX,VY,VZ,LT,RG,RR
0,2.461042e+06,2026-01-01 00:00:00,1.011876e+06,-343855.046085,1524.008884,3.512206,10.308045,0.444561,3.564819,1.068706e+06,0.009472
1,2.461042e+06,2026-01-01 01:00:00,1.023837e+06,-306522.991828,3123.045107,3.131622,10.429656,0.443693,3.564936,1.068741e+06,0.010036
2,2.461042e+06,2026-01-01 02:00:00,1.034419e+06,-268778.391867,4717.880593,2.746856,10.537211,0.442227,3.565060,1.068778e+06,0.010584
3,2.461042e+06,2026-01-01 03:00:00,1.043610e+06,-230672.111552,6306.368327,2.358432,10.630567,0.440167,3.565191,1.068817e+06,0.011118
4,2.461042e+06,2026-01-01 04:00:00,1.051396e+06,-192255.497384,7886.370396,1.966880,10.709600,0.437514,3.565327,1.068858e+06,0.011639

In [ ]:
# ============================================================
# Construction des transitions — Ganymède 2026
# ============================================================

transitions_ganymede_2026 = construire_transitions(
    ganymede_2026,
    "Ganymede"
)

print("Dimensions :", transitions_ganymede_2026.shape)
print(
    "Valeurs manquantes :",
    transitions_ganymede_2026.isna().sum().sum()
)
print(
    "D_T moyen :",
    transitions_ganymede_2026["D_T"].mean()
)
print(
    "D_T min :",
    transitions_ganymede_2026["D_T"].min()
)
print(
    "D_T max :",
    transitions_ganymede_2026["D_T"].max()
)

display(transitions_ganymede_2026.head())

Dimensions : (8760, 9)
Valeurs manquantes : 0
D_T moyen : 39166.90819744146
D_T min : 39053.483076601035
D_T max : 39279.164734426005

,Satellite,Datetime,dX,dY,dZ,dVX,dVY,dVZ,D_T
0,Ganymede,2026-01-01 01:00:00,11960.222503,37332.054257,1599.036223,-0.380584,0.121611,-0.000868,39233.736939
1,Ganymede,2026-01-01 02:00:00,10582.436369,37744.599961,1594.835486,-0.384766,0.107555,-0.001465,39232.464694
2,Ganymede,2026-01-01 03:00:00,9190.537072,38106.280316,1588.487734,-0.388424,0.093356,-0.002061,39231.082886
3,Ganymede,2026-01-01 04:00:00,7786.421278,38416.614167,1580.002068,-0.391552,0.079033,-0.002653,39229.593510
4,Ganymede,2026-01-01 05:00:00,6372.000856,38675.190427,1569.390490,-0.394148,0.064605,-0.003242,39227.996838

In [ ]:
observables_ganymede_2026_base, transitions_ganymede_2026_gvh = (
    calculer_observables_gvh_base(
        transitions_ganymede_2026,
        satellite="Ganymede",
        quantile_seuil=0.95
    )
)

display(observables_ganymede_2026_base)

,Satellite,Annee,N_etats,N_transitions,D_T_mean,S_T,S_T_norm,D_T_min,D_T_max,D_c,u_c,R_super
0,Ganymede,2026,8761,8760,39166.908197,56.903928,0.001453,39053.483077,39279.164734,39255.279355,0.894163,0.05

In [ ]:
# ============================================================
# Observables angulaires — Ganymède 2026
# ============================================================

observables_ganymede_2026_angles, angles_ganymede_2026 = (
    calculer_observables_angulaires(
        transitions_ganymede_2026,
        satellite="Ganymede",
        annee=2026
    )
)

display(observables_ganymede_2026_angles)

print("\nContrôles :")
print(
    "Nombre attendu d'angles :",
    len(transitions_ganymede_2026) - 1
)
print(
    "Nombre calculé :",
    angles_ganymede_2026["theta_deg"].notna().sum()
)
print(
    "Valeurs manquantes :",
    angles_ganymede_2026["theta_deg"].isna().sum()
)

display(angles_ganymede_2026.head())

,Satellite,Annee,N_angles,theta_mean,theta_median,theta_std,theta_min,theta_max,R_90,R_170,R_175,R_180
0,Ganymede,2026,8759,2.096567,2.096544,0.003053,2.090579,2.102931,0.0,0.0,0.0,0.0

Contrôles :
Nombre attendu d'angles : 8759
Nombre calculé : 8759
Valeurs manquantes : 0

  Satellite            Datetime  theta_deg
0  Ganymede 2026-01-01 02:00:00   2.100499
1  Ganymede 2026-01-01 03:00:00   2.100433
2  Ganymede 2026-01-01 04:00:00   2.100349
3  Ganymede 2026-01-01 05:00:00   2.100249
4  Ganymede 2026-01-01 06:00:00   2.100135

In [ ]:
# ============================================================
# Fusion des observables Ganymède 2026
# ============================================================

observables_ganymede_2026 = (
    observables_ganymede_2026_base
    .merge(
        observables_ganymede_2026_angles,
        on=["Satellite", "Annee"],
        how="left"
    )
)

display(observables_ganymede_2026)

,Satellite,Annee,N_etats,N_transitions,D_T_mean,S_T,S_T_norm,D_T_min,D_T_max,D_c,...,N_angles,theta_mean,theta_median,theta_std,theta_min,theta_max,R_90,R_170,R_175,R_180
0,Ganymede,2026,8761,8760,39166.908197,56.903928,0.001453,39053.483077,39279.164734,39255.279355,...,8759,2.096567,2.096544,0.003053,2.090579,2.102931,0.0,0.0,0.0,0.0

In [ ]:
observables_ganymede_2026.to_csv(
    "/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Ganymede_Observables_2026.csv",
    index=False
)

print("Export terminé : GVH_Ganymede_Observables_2026.csv")

Export terminé : GVH_Ganymede_Observables_2026.csv

In [ ]:
from pathlib import Path

dossier = Path("/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026")

for f in sorted(dossier.glob("*.csv")):
    print(f.name)

GVH_Europa_Angles_2000.csv
GVH_Europa_Observables_2026.csv
GVH_Europa_Transitions_2000.csv
GVH_Ganymede_Angles_2000.csv
GVH_Ganymede_Observables_2026.csv
GVH_Ganymede_Transitions_2000.csv
GVH_Io_Angles_2000.csv
GVH_Io_Transitions_2000.csv
GVH_Jovian_Data_Validation_2000.csv
GVH_Jovian_Observables_2000.csv
GVH_Jovian_Observables_2013.csv

In [ ]:
from pathlib import Path

for f in Path("/content/drive/MyDrive").rglob("*Io*.csv"):
    print(f)

/content/drive/MyDrive/Io_Horizons_Jovicentric_Vector_2026_1h_RAW.csv
/content/drive/MyDrive/JPL_Horizons_Io_2000_1h.csv
/content/drive/MyDrive/    NASA_JPL_Io_StateVectors_2013.csv
/content/drive/MyDrive/Saved from Chrome/GVH_Io_Validation_0.1.csv
/content/drive/MyDrive/Saved from Chrome/GVH_Io_Observables_0.1.csv
/content/drive/MyDrive/Saved from Chrome/GVH_Io_FFT_0.1.csv
/content/drive/MyDrive/Saved from Chrome/GVH_Io_Closure_0.1.csv
/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Io_Transitions_2000.csv
/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Io_Angles_2000.csv

In [ ]:
io = pd.read_csv(
    "/content/drive/MyDrive/Saved from Chrome/GVH_Io_Observables_0.1.csv"
)

europa = pd.read_csv(
    "/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Europa_Observables_2026.csv"
)

ganymede = pd.read_csv(
    "/content/drive/MyDrive/GVH_Jovian_Comparison_2000_2026/GVH_Ganymede_Observables_2026.csv"
)

In [ ]:
io = pd.read_csv(
    "/content/drive/MyDrive/Saved from Chrome/GVH_Io_Observables_0.1.csv"
)

display(io)

          Observable        Valeur
0     N_observations   8761.000000
1      N_transitions   8760.000000
2        D_T_mean_km  62356.220153
3         D_T_std_km    182.102162
4       D_T_norm_std      0.002920
5         D_T_min_km  62095.619747
6      D_T_median_km  62354.853614
7         D_T_max_km  62619.610046
8             D_c_km  62611.516788
9            R_super      0.050000
10    theta_mean_deg      8.478704
11     theta_std_deg      0.024559
12     theta_min_deg      8.443628
13  theta_median_deg      8.478489
14     theta_max_deg      8.514492
15             R_180      0.000000

In [ ]:
ligne.strip().split(",")

['*******************************************************************************']

In [ ]:
from pathlib import Path

chemin_io_2026 = Path(
    "/content/drive/MyDrive/Io_Horizons_Jovicentric_Vector_2026_1h_RAW.csv"
)

with open(
    chemin_io_2026,
    "r",
    encoding="utf-8",
    errors="replace"
) as fichier:
    lignes_io = fichier.readlines()

positions_soe = [
    i for i, ligne in enumerate(lignes_io)
    if "$$SOE" in ligne
]

positions_eoe = [
    i for i, ligne in enumerate(lignes_io)
    if "$$EOE" in ligne
]

print("Fichier présent :", chemin_io_2026.exists())
print("Nombre total de lignes :", len(lignes_io))
print("Positions $$SOE :", positions_soe)
print("Positions $$EOE :", positions_eoe)

Fichier présent : True
Nombre total de lignes : 35153
Positions $$SOE : [39]
Positions $$EOE : [35084]